// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYVKrFk1eA9gNtxQEtl6-NsdpcAaMe9Zc',
    appId: '1:931386117416:web:58890968fe846cc130941d',
    messagingSenderId: '931386117416',
    projectId: 'whatsapp-3b681',
    authDomain: 'whatsapp-3b681.firebaseapp.com',
    storageBucket: 'whatsapp-3b681.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOfHvGmFDqRNAGbfNzGjUoFzUUswS7RI',
    appId: '1:931386117416:android:5fe00ffb27bbe6b030941d',
    messagingSenderId: '931386117416',
    projectId: 'whatsapp-3b681',
    storageBucket: 'whatsapp-3b681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXAnX5tX43MKDgkObnftXdZ65jFtiuYqI',
    appId: '1:931386117416:ios:ec301859ba8df7ec30941d',
    messagingSenderId: '931386117416',
    projectId: 'whatsapp-3b681',
    storageBucket: 'whatsapp-3b681.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXAnX5tX43MKDgkObnftXdZ65jFtiuYqI',
    appId: '1:931386117416:ios:ec301859ba8df7ec30941d',
    messagingSenderId: '931386117416',
    projectId: 'whatsapp-3b681',
    storageBucket: 'whatsapp-3b681.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYVKrFk1eA9gNtxQEtl6-NsdpcAaMe9Zc',
    appId: '1:931386117416:web:fc540d7e8ddb1b2b30941d',
    messagingSenderId: '931386117416',
    projectId: 'whatsapp-3b681',
    authDomain: 'whatsapp-3b681.firebaseapp.com',
    storageBucket: 'whatsapp-3b681.firebasestorage.app',
  );
}
